### ISSUE TITLE
訳語の変更を反映

### ISSUE THREAD

**Issue by jtakiguchi** [Polymer-Japan/translation#95]
MTGで協議した以下の訳語を変更する。

変更レコード => チェンジレコード 
複雑なオブザーバー => コンプレックスオブザーバー
カスタム要素 => Custom Element(s)
要素 => エレメント
監視する=> リッスンする
監視可能 => 監視可能(observable)
Polymer要素 => Polymer Element
単純なオブザーバー =>シンプルオブザーバー

**Comment by ecouffes** [comment]
This issue was moved to Polymer-Japan/docs#113
